version: '3'

services:
  database:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=db_users
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017

  database_test:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=db_users_test
    volumes:
      - ./mongo-volume-test:/data/db
    ports:
      - 53272:53272
